# permissions for end users to edit ovnnorthds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovnnorthd-editor-role
rules:
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovnnorthds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovnnorthds/status
  verbs:
  - get
