---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovncentrals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovncentrals/finalizers
  verbs:
  - update
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovncentrals/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovsdbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovsdbclusters/finalizers
  verbs:
  - update
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovsdbclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovsdbservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovsdbservers/finalizers
  verbs:
  - update
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovsdbservers/status
  verbs:
  - get
  - patch
  - update
