---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.openstack.org
  resources:
  - dnsdata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovncontroller
  verbs:
  - watch
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovncontrollers
  - ovndbclusters
  - ovnnorthds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovncontrollers/finalizers
  - ovndbclusters/finalizers
  - ovnnorthds/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovncontrollers/status
  - ovnnorthds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ovn.openstack.org
  resources:
  - ovndbclusters/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - security.openshift.io
  resourceNames:
  - restricted-v2
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - topology.openstack.org
  resources:
  - topologies
  verbs:
  - get
  - list
  - update
  - watch
