apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
  labels:
    osp/net: data-centre3
    service: ovn-controller
  name: data-centre3
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "data-centre3",
      "type": "bridge",
      "bridge": "ospbr3",
      "ipam": {}
    }
