apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
  labels:
    osp/net: datacentre2
    service: ovn-controller
  name: datacentre2
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "datacentre2",
      "type": "bridge",
      "bridge": "ospbr2",
      "ipam": {}
    }
